### ISSUE TITLE
Add readline support

### ISSUE THREAD

**Issue by simos** [ilstam/Hunt#1]
With readline support, it would be feasible to add usability features such as
1. completion support
2. command history

As an example, try the code at http://sunsite.ualberta.ca/Documentation/Gnu/readline-4.1/html_node/readline_45.html
The same document has full documentation for use of the readline library.

**Comment by ilstam** [comment]
I'll surely give it a try when I will have the time.

Thank you very much!

**Comment by ilstam** [comment]
GNU readline support added successfully!
