### ISSUE TITLE
Add gettext support

### ISSUE THREAD

**Issue by simos** [ilstam/Hunt#2]
With gettext support, Hunt will be able to internationalised and then localised in different languages.
For more on gettext support, see http://www.gnu.org/software/gettext/manual/gettext.html

**Comment by simos** [comment]
See also http://git.savannah.gnu.org/cgit/hello.git which has a hello world application that uses gettext in an automated way (using autotools).

**Comment by ilstam** [comment]
GNU gettext support added successfully. 
Hunt translated into Greek.
